### ISSUE TITLE
Pack kernel in a function for Benchmark mode

### ISSUE THREAD

**Issue by christiealappatt** [RRZE-HPC/kerncraft#107]
It was observed that for some strange reason there are multiple effects that could effect benchmarking if the kernel and allocations are done on a single file. It would be nice if the kernel is moved to a separate .c file and compiled separately.

**Comment by cod3monk** [comment]
Yes, but it's a rather fundamental change and realted to #56.

**Comment by cod3monk** [comment]
@rrzeschorscherl @christiealappatt 
Can it be assumed that having the kernel in a separate function and file is always best? This would also entail that the compiler is unable to relate aligned mallocs to the pointers used in the kernel.

If the answer is yes, I can go on an implement this.

**Comment by rrzeschorscherl** [comment]
Yes, I believe this is the case. If we need to tell the compiler about alignment, this should be done using directives or compiler options.

**Comment by cod3monk** [comment]
Could you check the latest commit c60baf8043e4da8d8d66da7575021c2f4c6c78af? This should implement this feature.

**Comment by christiealappatt** [comment]
Seems fine. Works correctly for the example where I came across this problem.
