### ISSUE TITLE
Intel compiler requires zmm-usage option for AVX512 code

### ISSUE THREAD

**Issue by sharkovsky** [RRZE-HPC/kerncraft#125]
Hi, 

I think that a missing `-qopt-zmm-usage=high` in machine files such as  `SkylakeSP_Gold-6148.yml` might be preventing correct generation of AVX512 code when using the Intel compiler, which in turn may lead to wrong in-core predictions by IACA. 

Could this be the case?

Thanks!

**Comment by cod3monk** [comment]
You are correct. We've had an internal version which had it fixed, but forgot to publish it.
