### ISSUE TITLE
likwid_bench_auto problems

### ISSUE THREAD

**Issue by thextor** [RRZE-HPC/kerncraft#46]
I'm trying to generate a machine file for an Intel Skylake CPU (I5-6600) and continue to run into problems. Using Python 2.7.9 I installed the latest Kerncraft version with pip.

There is a typo in the current likwid_bench_auto.py:48
>  'cores per NUMA domain': **codes**_per_numa_domain,

There also seem to be problems with the PrefixedUnit type in lines 232 and 233. Sadly the script stops with an error.
> sizes_per_core = [t/cores[i] for i, t in enumerate(total_sizes)]
> sizes_per_thread = [t/threads[i] for i, t in enumerate(total_sizes)]

Error:
> ./likwid_bench_auto > mf.yml
> Traceback (most recent call last):
>  File "./likwid_bench_auto", line 11, in <module>
>    sys.exit(main())
>  File "/mnt/home/stud-erha1011/workspace/kerncraft/kerncraft_env/local/lib/python2.7/site-packages/kerncraft/likwid_bench_auto.py", line 206, in main
    sizes_per_core = [t/cores[i] for i, t in enumerate(total_sizes)]
TypeError: unsupported operand type(s) for /: 'PrefixedUnit' and 'int'

**Comment by cod3monk** [comment]
If problems persist, please reopen. I have also added a test case to spot problems earlier in likwid_bench_auto.
