### ISSUE TITLE
phinally.yaml not available

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#47]
In the documentation/ usage it is suggested to doqnload the machine file phinally.yaml via
`wget https://raw.githubusercontent.com/RRZE-HPC/kerncraft/master/examples/machine-files/phinally.yaml`

It returns a
ERROR 404: Not Found

Documentation should be modified.

**Comment by cod3monk** [comment]
You're right, I renamed the files from our cluster names to the underlying CPU model names. I will update the README file.

Thank you for reporting this issue.
