### ISSUE TITLE
Extend search path for IACA

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#63]
I would like to have an extra path for the search if possible. I installed kerncraft via EasyBuild (a scientific software management tool): it makes the software available as a modulefile. I also installed IACA through EasyBuild. When I run kerncraft with the ECM model I get the following error:

```
[guerrera@dmi-cl-login ~]$ kerncraft -p ECM code.c -m HaswellEX_E5-2695v3.yml -D M 200 -D N 200
================================== kerncraft ===================================
cazzo.c                                               -m HaswellEX_E5-2695v3.yml
-D M 200 -D N 200
------------------------------------- ECM --------------------------------------
IACA analysis failed: No IACA installation found in ['/users/staff/ifi/guerrera/.kerncraft/iaca/lin64/', '/users/staff/ifi/guerrera/.local/easybuild/software/kerncraft/20171205-foss-2017a-Python-3.6.1/lib/python3.6/site-packages/kerncraft-0.5.9-py3.6.egg/kerncraft/iaca/lin64/']. Run iaca_get command to fix this issue.
```

IACA is not installed in that path, but is installed and available in the environment at $EBROOTIACA
Or simply test if iaca is present, because being the the PATH, you can directly call as iaca and you get it running.

Is it possible to add it to the search path or test if it is available?

**Comment by cod3monk** [comment]
Kerncraft needs a special installation of IACA, therefore the unusual search paths. Have you tried using `iaca_get`, as the error message suggests?

**Comment by sguera** [comment]
I already installed IACA in the past with iaca_get (get_iaca), when trying kerncraft. I was doing the next step which is a reproducible installation of the softwares. One way to do so is using EasyBuild. In orde to do so you must specify the dependencies and so did I. Once installed I get a module for Kerncraft and when I load it, since it has a dependency on IACA, the IACA module gets loaded too.

I did not know that you need a special installation of IACA. I try to figure out a workaround for this then.

**Comment by cod3monk** [comment]
Intel started dropping support for older micro architectures, which means that three versions of IACA need to installed in parallel. The `iaca_get` script takes care of that.

You could package the `iaca_get` script. It only depends on `requests`. But in any case you will need to get IACA directly from Intel, since they don't grant permission to distribute it. Thus, the `iaca_get --I-accept-the-Intel-What-If-Pre-Release-License-Agreement-and-please-take-my-soul` workaround.

**Comment by sguera** [comment]
I see. I can make it. My only "problem" is that I will get IACA installed not inside kerncraft, but I will get something like:
$EBROOT/software/i/IACA/2.2
$EBROOT/software/i/IACA/2.3
$EBROOT/software/i/IACA/3.0
I can place all of them as a dependency of kerncraft so all of them will be available, but I still need that kerncraft looks for them not in .kerncraft but in that path.

Let's freeze the discussion anyway. Since it appears to give a few troubles I will just install them through iaca_get for now...

Thanks for the explanation
