### ISSUE TITLE
IACA analysis fails due to pointer_increment

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#71]
When running:
```
 kerncraft -p ECM stencil.c -m Intel_Xeon_CPU_X5650_2.67GHz_mod.yml  -D M 1224 -D N 1224
```

I get:
```
kerncraft                                    
stencil.c -m Intel_Xeon_CPU_X5650_2.67GHz_mod.yml
-D M 1224 -D N 1224
------------------------------------- ECM --------------------------------------
IACA analysis failed: pointer_increment could not be detected automatically. Use --pointer-increment to set manually to byte offset of store pointer address between consecutive assembly block iterations.
```

Content of stencil.c:
```
double a[M][N];
double b[M][N];
double W[M][N][2];

for(int j=1; j < M-1; j++){
for(int i=1; i < N-1; i++){
b[j][i] = W[j][i][0] * a[j][i]
+ W[j][i][1] * ((a[j][i-1] + a[j][i+1]) + (a[j-1][i] + a[j+1][i]))
;
}
}
```

**Comment by sguera** [comment]
It also fails with this code:
```
double a[M][N];
double b[M][N];
double c0;
double c1;
double c2;

for(int j=1; j < M-1; j++){
for(int i=1; i < N-1; i++){
b[j][i] = c0 * a[j][i]
+ c1 * (a[j][i-1] + a[j-1][i] + a[j+1][i] + a[j][i+1])
+ c2 * (a[j-1][i-1] + a[j+1][i-1] + a[j-1][i+1] + a[j+1][i+1])
;
}
}
```

**Comment by cod3monk** [comment]
you can resolve this by manually providing the pointer increment via `--pointer-increment`. For me to investigate this issue further, you will need to provide the generated assembly file.

**Comment by cod3monk** [comment]
Have you tried the latest kerncraft version? Did it solve the problem? If not, could you provide the generated assembly file for debugging purposes.

**Comment by sguera** [comment]
I just tried for both the codes. I still get the same error with the latest kerncraft.
I attach the 2 assembly files.

[2D-5pt-variable.s.txt](https://github.com/RRZE-HPC/kerncraft/files/1618418/2D-5pt-variable.s.txt)
[2D-5pt-constant.s.txt](https://github.com/RRZE-HPC/kerncraft/files/1618419/2D-5pt-constant.s.txt)

**Comment by cod3monk** [comment]
It is not en error, you can always set the pointer increment: for the 2D-5pt-variable code use `--pointer-increment 16` and for the 2D-5pt-constant code use `--pointer-increment 8`.

I will try to tweak the heuristics to also handle the codes you provided, but there will always be cases  where it fails an the loop or pointer increment needs to be manually given.

**Comment by sguera** [comment]
I understand.. the problem is when we want to use it automatically on all the bouquet of stencils that can be generated through STEMPEL (generate each possible combination + for each code kerncraft analysis + for each code run through PROVA! and then validate)

**Comment by sguera** [comment]
For me to understand how to do it (even if not automatically), can you explain or give me a reference in how to identify the correct pointer increment (and then manually specify it?

**Comment by cod3monk** [comment]
You need to identify the loop in the assembly code. `iaca_marker` helps here, most of the time the default selection is correct. Then in the assembly you will need to look for the store memory references and identify the increment from one block iteration to the next.

**Comment by cod3monk** [comment]
The two cases you provided are now recognized automatically, but as said before: there will always be situations where the heuristic fails.
