### ISSUE TITLE
Pragma in Inner loop fails 

### ISSUE THREAD

**Issue by christiealappatt** [RRZE-HPC/kerncraft#79]
Please check the following code, I get the following error: _AssertionError: all statements before the for loop need to be declarations or pragmas_. This happens if pragma appears in the inner loops.

[pragma_inner_loop_err.tar.gz](https://github.com/RRZE-HPC/kerncraft/files/1574793/pragma_inner_loop_err.tar.gz)

**Comment by cod3monk** [comment]
Note: The code is wrong according to the way pycparser handles pragmas. It would interpret the outer for loop to iterate over the pragma statement, and the two other loops to be their own loop nest
