### ISSUE TITLE
LC mode overcounting data transfers on this particaular code

### ISSUE THREAD

**Issue by christiealappatt** [RRZE-HPC/kerncraft#82]
In the code attached LC running kerncraft in LC mode predicts 7 misses and 1 evict, but actually the value is 6 misses and 1 evict. The SIM mode is fine here. An example run :  **kerncraft -p ECM -m Emmy.yml -D n 1000000 -D s 4 LC_lji.c --cache-predictor=LC -vvv**

[LC_overpred.tar.gz](https://github.com/RRZE-HPC/kerncraft/files/1589062/LC_overpred.tar.gz)

**Comment by cod3monk** [comment]
`A` was considered as a variably accessed array, eventhough it only varies with `l`,  and therefore accounted wrongfully for one additional access on all cache levels. Will be fixt shortly.
