### ISSUE TITLE
Cache simulation "explodes" with full caching

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/kerncraft#89]
When executing this code with `-D M1 128 -D K 128 -D N2 128 -D N1 128 -p ECMData`, the cache simulator detects full caching opportunity and tries to simulate all loop iterations (268.435.456 with 805.306.368 addresses). That is not feasible and needs to be solved some other way.

```
double a[M1][K];
double b[K][N2][N1];
double c[M1][N1][N2];
double s;

for(int m1=1; m1<M1-1; ++m1)
    for(int n1=1; n1<N1-1; ++n1)
        for(int n2=1; n2<N2-1; ++n2)
            for(int k=1; k<K-1; ++k)
                c[m1][n1][n2] += a[m1][k] + b[k][n2][n1];

```

Code provided by @springer13

**Comment by springer13** [comment]
thanks for looking into it. I'll keep an eye on this post.

**Comment by cod3monk** [comment]
I believe this issue has resolved since. Can you confirm? I am unable to reproduce the issue with the lastest git version.
