### ISSUE TITLE
Add compiler options from machine file also for linking

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/kerncraft#93]
0.6.6

When compiling the kernel code, the options from the machine file are used. However, when linking to the executable, those options are omitted. Linking may fail in cases where compile options are also needed for linking. Example: -fopenmp

Request: Either include the compiler options also at the linker stage or (preferred) provide separate entry in machine file for linker options (per compiler).

**Comment by cod3monk** [comment]
All compiler arguments from the machine file are now used during linking.
