### ISSUE TITLE
IACA fails due to pointer increment

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/kerncraft#98]
The error is known. I will use this issue to collect the cases where the analysis fails.
I am using kerncraft 0.6.10 and gcc-7.3.0.

When running the following command:
```
kerncraft -P SIM -p Roofline -p ECM /home/hpc/ihpc/ihpc07/THESIS/stempelvalidation/stencils/2D/1r/isotropic/star/variable/2d-1r-isotropic-variable-star-stencil.c -m IvyBridgeEP_E5-2660v2.yml -D M 5000 -D N 5000 --unit=FLOP/s --cores=1 -vv
```

I get the following error:
```
IACA analysis failed: pointer_increment could not be detected automatically. Use --pointer-increment to set manually to byte offset of store pointer address between consecutive assembly block iterations.
```

The machine file is available in kerncraft.

The source code is:
```
double a[M][N];
double b[M][N];
double W[M][N][2];

for(int j=1; j < M-1; j++){
for(int i=1; i < N-1; i++){
b[j][i] = W[j][i][0] * a[j][i]
+ W[j][i][1] * ((a[j][i-1] + a[j][i+1]) + (a[j-1][i] + a[j+1][i]))
;
}
}
```

**Comment by cod3monk** [comment]
Please provide the compiled assembly where the analysis fails, including the block/label that should be selected and pointer increment you expect.

**Comment by sguera** [comment]
I can provide the assembly.

If you are keen to solve the issue feel free to have a look at it.
[2d-1r-isotropic-variable-star-stencil.s.txt](https://github.com/RRZE-HPC/kerncraft/files/2259804/2d-1r-isotropic-variable-star-stencil.s.txt)
